# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8dee5e68b4ba38d9f5d195df216a8b2e033452a6138257afa84dacb55b220e454fd6a294c94e04776c75e11eedb108a1ae3cddff353f3d11cafdb574d510831

test:
  secret_key_base: be46f01b91535fcb85fd6b30120abf2d9030c437ba5cfaf3c240935259ca91074b650db5f0a59a00316015ea40d46faf8ddc1c1e82b71ea984a34b455b188150

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
